server:
  port: 8094
  servlet:
    contextPath: /api/v1

spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  application:
    name: E-shop message broker
    version: 1.0.0