server:
  port: 8091
  servlet:
    contextPath: /api/v1

spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  application:
    name: E-shop nofification
    version: ${version}
  http:
    converters:
      preferred-json-mapper: gson
  mail:
    host: smtp.gmail.com
    port: 587
    username: otus.sa.eshop.alexei@gmail.com
    password: otus.sa.eshop.alexei.pass
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com